name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate 3D Graph
        uses: saraswatmks/github-profile-3d-contrib@master
        with:
          username: ZaheerAhmedkhan65
          output_file: profile-3d-contrib.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
